 GET http://localhost:5108/games

###
 GET http://localhost:5108/games/1


###

POST http://localhost:5108/games
Content-Type: application/json

{
    "name": "New Game",
    "genre": "Adventure",
    "price": 49.99,
    "releaseDate": "2024-10-01"
}

###
    PUT http://localhost:5108/games/1
    Content-Type: application/json

    {
        "name": "Updated Game",
        "genre": "UpdatedAction",
        "price": 159.99,
        "releaseDate": "2024-11-01"
    }

###
    DELETE http://localhost:5108/games/1
    